### PR TITLE
fix: added / to baseUrl for instant preview

### PR DESCRIPTION
**Pull request by kendallstrautman**

### CODE REVIEW

**Comment by DirtyF** [comment]
Duplicate of #7

**Comment by kendallstrautman** [comment]
@DirtyF - since this one has no merge conflicts, maybe its better to merge it than #7. Someone else had an issue with this baseurl param today, do you have admin access to accept this merge?

**Comment by DirtyF** [comment]
of course not :)

**Comment by DirtyF** [comment]
@kendallstrautman now we have let me fix the other PR.

**Pull request closed without merging**
